### PR TITLE
Fix command in markup control in HierarchyRepeater

### LINKED ISSUE #1422: HiearchyRepeater doesn't work in markup controls
Specifically, commands from inside a markup control in a HierarchyRepeater ItemTemplate fail. See the `WithMarkupControl` sample in the `tests/hierarchy-repeater` branch.

### PR DESCRIPTION
**Pull request by exyi**
Resolves  #1422

I'd suggest reviewing by commits, there is number of changes, many of them to the testing infra or error handling.

UI test is missing

### CODE REVIEW

File: src/Tests/ControlTests/HierarchyRepeaterTests.cs [hunk 1]
```diff
@@ -40,6 +41,42 @@ public async Task UsageWithThisInBindings()
...
+                        @property DotVVM.Framework.Binding.Expressions.Command Click
+
+                                    <dot:Button Click={command: _control.Click()} Text={value: _this.Label} />
+                        """
+                },
+                fileName: "CommandInMarkupControl" + (clientRendering ? "Client" : "Server")
+            );
+
+            // await r.RunCommand("_control.Click()", vm => vm is BasicTestViewModel.SaneHierarchicalItem { Label: "A_1_2" });
+            // Assert.AreEqual("A_1_2", (string)r.ViewModel.SelectedLabel);
```
Comment (exyi) [inline src/Tests/ControlTests/HierarchyRepeaterTests.cs:72]: add this assert back

File: src/Framework/Framework/Hosting/ErrorPages/ErrorPageTemplate.cs [hunk 2]
```diff
@@ -108,7 +108,7 @@ public string TransformText()
             <button type=button id=save-and-share-button class=execute title='Saves the error as HTML so you can share it with your coworkers'>Save and Share</button>
         </div>
         <h1>Server Error, HTTP {ErrorCode}: {WebUtility.HtmlEncode(ErrorDescription)}</h1>
-        <p class=summary>{WebUtility.HtmlEncode(Summary)}</p>
+        <p class=summary><pre class=not-monospace>{WebUtility.HtmlEncode(Summary)}</pre></p>
```
Comment (exyi) [inline src/Framework/Framework/Hosting/ErrorPages/ErrorPageTemplate.cs:111]: not needed

**Review by acizmarik — APPROVED** [review]
