### PR TITLE
Fixed inline editing for nested GridViews

### LINKED ISSUE #864: Issue with InlineEditing in nested GridViews
One of our Dev Advocates found out that the ` InlineEditing` feature doesn't work in nested `GridView` controls.
Here is a repo with the problem: https://github.com/miroprocessor/dotvvm-nestedgrids

### PR DESCRIPTION
**Pull request by acizmarik**
This PR fixes inline editing for nested `GridView`s. Resolves #864.

### CODE REVIEW

**Review by tomasherceg — APPROVED** [review]

File: src/DotVVM.Framework/Configuration/UserColumnMappingCache.cs [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+using System.Threading.Tasks;
+using DotVVM.Framework.Controls;
+using DotVVM.Framework.ViewModel;
+
+namespace DotVVM.Framework.Configuration
+{
+    public class UserColumnMappingCache
+    {
+        private ConcurrentDictionary<Type, Dictionary<string, string>> mappingCache;
+        private IPropertySerialization propertySerialization;
```
Comment (exyi) [inline src/DotVVM.Framework/Configuration/UserColumnMappingCache.cs:15]: `IPropertySerialization` should not be used to figure out the property names. It can be renamed later using this API https://github.com/riganti/dotvvm/pull/262.

You should call `IViewModelSerializationMapper.GetMap` to get the real mapping of all properties.

File: src/DotVVM.Framework/Resources/Scripts/DotVVM.ts [hunk 2]
```diff
@@ -1447,7 +1447,18 @@ class DotVVM {
...
-                (bindingContext, value) => bindingContext.extend({ $gridViewDataSet: value, [foreachCollectionSymbol]: dotvvm.evaluator.getDataSourceItems(value) }),
+                (bindingContext, value, allBindings) => bindingContext.extend({
+                    $gridViewDataSet: value,
+                    [foreachCollectionSymbol]: dotvvm.evaluator.getDataSourceItems(value),
+                    $gridViewDataSetHelper: {
+                        columnMapping: allBindings.get("gridViewDataSetColumnMapping"),
+                        isInEditMode: function ($context) {
+                            let columnName = $context.$gridViewDataSet().RowEditOptions().PrimaryKeyPropertyName();
+                            columnName = this.columnMapping[columnName] || columnName;
+                            return ko.unwrap($context.$gridViewDataSet().RowEditOptions().EditRowId) === ko.unwrap($context.$data[columnName]);
```
Comment (exyi) [inline src/DotVVM.Framework/Resources/Scripts/DotVVM.ts:1458]: Is there a case when `EditRowId` is not observable? That would clearly be a bug - we should not use `ko.unwrap` here

File: src/DotVVM.Framework/Configuration/UserColumnMappingCache.cs [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+
+        public UserColumnMappingCache(IPropertySerialization propertySerialization)
+        {
+            this.propertySerialization = propertySerialization;
+            this.mappingCache = new ConcurrentDictionary<Type, Dictionary<string, string>>();       
+        }
+
+        public Dictionary<string, string> GetMapping(Type type)
```
Comment (exyi) [inline src/DotVVM.Framework/Configuration/UserColumnMappingCache.cs:23]: We should return `IReadOnlyDictionary` to prevent mutation of the cached value.

File: src/DotVVM.Framework/Resources/Scripts/DotVVM.ts [hunk 4]
```diff
@@ -1408,7 +1408,7 @@ class DotVVM {
                     if (!isInitial) {
                         ko.virtualElements.setDomNodeChildren(element, ko.utils.cloneNodes(savedNodes!));
                     }
-                    ko.applyBindingsToDescendants(makeContextCallback(bindingContext, rawValue), element);
+                    ko.applyBindingsToDescendants(makeContextCallback(bindingContext, rawValue, _allBindings), element);
```
Comment (exyi) [inline src/DotVVM.Framework/Resources/Scripts/DotVVM.ts:1411]: `_allBindings` was named with the underscore since the parameter was unused. As we use it now, the name should not start with underscore.

**Review by exyi — CHANGES_REQUESTED** [review]

**Review by exyi — APPROVED** [review]
